os:
  - linux

cache: apt

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo add-apt-repository -y ppa:rbose-debianizer/automake
  - sudo apt-get update -qq
#  - sudo apt-get install -y automake1.12
  - sudo apt-get install -y wine1.7

language: c

compiler:
  - gcc

script:
  - wineboot
  - export EXEEXT=.exe
  - export WINEDEBUG=-all
  - ./zz_clipboard_test.exe
