os:
  - linux

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y wine1.7

language: c

compiler:
  - gcc

script:
  - wineboot
  - export EXEEXT=.exe
  - export WINEDEBUG=+all
  - chmod +x ./zz_clipboard_test.exe
  - ./zz_clipboard_test.exe 1.copy_file
